name = "Bijections"
uuid = "e2ed5e7c-b2de-5872-ae92-c73ca462fb04"
authors = ["Ed Scheinerman <ers@jhu.edu>"]
version = "0.2.2"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
